### ISSUE TITLE
Could not build. Documentation or source files may be incomplete

### ISSUE THREAD

**Issue by system198** [zaksabeast/DreamRadarCartRedirect#12]
Tried using the command as mentioned in the Readme but it gives me an error:

```
armips transporter.s -strequ SD_SAVE_PATH "/nds/saves/black2.sav" -strequ GAME_ID "IREO"
transporter.s(2) fatal error: Could not open file transporter.bin
Aborting.
```

armips source is from https://github.com/Kingcom/armips
while flips at https://www.romhacking.net/download/utilities/1040/

**Comment by zaksabeast** [comment]
You need to dump `code.bin` from transporter using GodMode9, then rename it to `transporter.bin`, and place it in the root of the repository.
