### ISSUE TITLE
Dream Radar and Transporter not working?

### ISSUE THREAD

**Issue by BuggaKyu** [zaksabeast/DreamRadarCartRedirect#13]
I've done as the usage page said to do with the Luma folders and the .ips and saves but it doesn't seem to read any of the roms on my 3ds. Did I miss a step somewhere?

**Comment by UltimateViolet** [comment]
Having a similar issue. Tried renaming the files and made doubly sure everything was in the right place and that the luma TID folder was named correctly, but Dream Radar won't detect Black 2 and just sends me back to the title.

**Comment by zaksabeast** [comment]
Could you please boot your 3ds while holding select and post a picture of your current Luma version and settings?

**Comment by UltimateViolet** [comment]
I updated to the latest version before starting this and made sure game patching was enabled
![20230405_150116](https://user-images.githubusercontent.com/129917620/230122068-cf2e31b4-570f-4d71-924d-134a0b84166a.jpg)

**Comment by zaksabeast** [comment]
Excellent, thank you.

You made doubly sure everything was in the right place, but just to be triply sure, where are the patch and save files located on your sd card?

Are you using the international or Japanese version of Dream Radar?

**Comment by BuggaKyu** [comment]
![image](https://user-images.githubusercontent.com/129441297/230409790-2890f85d-944b-44c4-b611-f46b97f7cc99.png)
![image](https://user-images.githubusercontent.com/129441297/230409861-e9cf78ce-26e6-404d-93dc-01e7bebf46b0.png)
![image](https://user-images.githubusercontent.com/129441297/230409916-f724f557-ae2a-4e65-8744-4d1ff8ecdc4f.png)
![image](https://user-images.githubusercontent.com/129441297/230409975-8c5df36a-99b3-4a7b-93eb-a2c41e7bf96a.png)
These are the patches and the roms/saves and from the looks of it they are all in the right place. But it doesn't seem to work. (also this is the OP)

**Comment by UltimateViolet** [comment]
> Excellent, thank you.
> 
> You made doubly sure everything was in the right place, but just to be triply sure, where are the patch and save files located on your sd card?
> 
> Are you using the international or Japanese version of Dream Radar?

I'm using the international version of Dream Radar. I have also not tested with Transporter yet.
![image](https://user-images.githubusercontent.com/129917620/230468249-079960cf-b272-4675-999d-c94a44bb4946.png)
![image](https://user-images.githubusercontent.com/129917620/230468504-01c87081-739c-40b8-8c58-c295cfd1dfc9.png)
![image](https://user-images.githubusercontent.com/129917620/230468601-8b2c7e48-000d-4738-be17-22fa54985a52.png)

If you're wondering why it's listed as a USB drive, I'm using a USB card reader to connect it to my PC.

**Comment by DittoLink** [comment]
> Having a similar issue. Tried renaming the files and made doubly sure everything was in the right place and that the luma TID folder was named correctly, but Dream Radar won't detect Black 2 and just sends me back to the title.

What gameid is your black2?Official version can only recognize IREO.

**Comment by zaksabeast** [comment]
It looks like both of you need to rename `black2.ips` and `white2.ips` to `code.ips`.

> What gameid is your black2?Official version can only recognize IREO.

Each patch hardcodes the corresponding game id [in the makefile](https://github.com/zaksabeast/DreamRadarCartRedirect/blob/main/Makefile#L18), so the game will think IREO is inserted.

**Comment by BuggaKyu** [comment]
Should I also change the normal black.ips to code.ips? Also the change for the white2.ips worked!

**Comment by UltimateViolet** [comment]
> It looks like both of you need to rename `black2.ips` and `white2.ips` to `code.ips`.
> 
> > What gameid is your black2?Official version can only recognize IREO.
> 
> Each patch hardcodes the corresponding game id [in the makefile](https://github.com/zaksabeast/DreamRadarCartRedirect/blob/main/Makefile#L18), so the game will think IREO is inserted.

Changing the filename worked, thank you so much for your help!

**Comment by zaksabeast** [comment]
> Should I also change the normal black.ips to code.ips?

Yes, any patches need to be renamed to `code.ips`.

> Also the change for the white2.ips worked!

> Changing the filename worked, thank you so much for your help!

Awesome, I'm glad both of you were able to get it working.
