### ISSUE TITLE
Expanding readme

### ISSUE THREAD

**Issue by alvv-z** [zaksabeast/DreamRadarCartRedirect#16]
Is there any interest in expanding the README to include instructions for dumping the .code and making the build instructions more detailed? If so, I could whip up a pull request.

**Comment by zaksabeast** [comment]
That would be awesome, thank you!

**Comment by Zafictus** [comment]
Hello,
I have been having troubles with launching the PokeTransporter after the patch. Thought the Dream Radar works like a charm, Transporter keeps crashing. 

Attached is the crash dump.
[crash_dump_00000005.zip](https://github.com/zaksabeast/DreamRadarCartRedirect/files/12305054/crash_dump_00000005.zip)

**Comment by zaksabeast** [comment]
@Zafictus Please open a new issue.  This issue was tracking readme updates and is now closed.
