### ISSUE TITLE
Poketransporter crashes when patch is used.

### ISSUE THREAD

**Issue by Zafictus** [zaksabeast/DreamRadarCartRedirect#18]
I have done exactly as the instruction dictate but the poketransporter keeps crashing.
I am attaching the crash dump here.
[crash_dump_00000005.zip](https://github.com/zaksabeast/DreamRadarCartRedirect/files/12309515/crash_dump_00000005.zip)

The DreamRadar patch works though.

Cheers!

**Comment by zaksabeast** [comment]
Hello!  Sorry to hear about the troubles.  I have limited time in the next few weeks to work on this, so it might be a bit before a resolution comes.  Thank you for posting the crash dump - that is very helpful.

In the meantime, here are a few questions to help gather information:
- Did you custom make the patch with a specific save path, or did you download the patch from the releases page?
- Does it work if you try [the v2.0.0 release](https://github.com/zaksabeast/DreamRadarCartRedirect/releases/tag/v2.0.0)?

**Comment by Zafictus** [comment]
Hello!
Thank you for your reply. Of course, take your time. 
I am using only the patches provided. Using v 3.0.0 as of now.
I will try the v2.0.0 and come back to you.

**Comment by Zafictus** [comment]
I just finished testing v2.0.0
It still crashes.
Here is the v2.0.0 crash dump as well.
[crash_dump_00000006.zip](https://github.com/zaksabeast/DreamRadarCartRedirect/files/12321618/crash_dump_00000006.zip)

**Comment by Zafictus** [comment]
Ok I solved the issue.
Apparently the version of poke transporter i had was not the v1.5 (5200) and that's the reason it was crashing. Now i installed the latest version and it works flawlessly.
