### ISSUE TITLE
Support for Gen IV

### ISSUE THREAD

**Issue by TonRZN** [zaksabeast/DreamRadarCartRedirect#19]
Does the patch supports the [Generation 4 game card inserted feature](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Dream_Radar#:~:text=Generation%20IV%20Game%20Card%20inserted*) ?

**Comment by KostaSaizo7** [comment]
You can use these cheats: https://gbatemp.net/threads/pokemon-dream-radar-cheats-spoof-gen-4-carts.549994/
