### ISSUE TITLE
Pokemon dream radar crashes when opened

### ISSUE THREAD

**Issue by Spas120** [zaksabeast/DreamRadarCartRedirect#22]
It says an exception occurred every time I try to open it so please help

**Comment by zaksabeast** [comment]
Please upload the luma crash dump or a picture of the exception occurred message from the 3ds.

**Comment by Spas120** [comment]
> Please upload the luma crash dump or a picture of the exception occurred message from the 3ds.

Here is the dmp file:  https://www.mediafire.com/file/pmbyindvz3b5z5v/crash_dump_00000003.dmp/file

**Comment by zaksabeast** [comment]
Hmm that's a loader module error, not Dream Radar.

Here are a few questions to help debug the issue:
- What version of luma do you have?
- Do you have any custom sysmodules that are not from luma?
- Do you have any additional mods, patches, or cheats for Dream Radar?

**Comment by Spas120** [comment]
> Hmm that's a loader module error, not Dream Radar.
> 
> Here are a few questions to help debug the issue:
> 
> * What version of luma do you have?
> * Do you have any custom sysmodules that are not from luma?
> * Do you have any additional mods, patches, or cheats for Dream Radar?

I'm using Luma 13.0.2 and the only Pokemon dream radar cheats I have is the save editor app for it and for the second question the answer is no and poke transporter redirect worked fine but the dream radar redirect didn't work

**Comment by zaksabeast** [comment]
Looking at the source for Luma's loader module, it looks like you might get `svcBreak` (the error from your crash dump) if the file is invalid.

I would try redownloading the patch and copying to your sd again.

If you used ftp previously, you might try plugging the sd into your computer directly.

**Comment by Spas120** [comment]
> Looking at the source for Luma's loader module, it looks like you might get `svcBreak` (the error from your crash dump) if the file is invalid.
> 
> I would try redownloading the patch and copying to your sd again.
> 
> If you used ftp previously, you might try plugging the sd into your computer directly.

I also opened the ips file in notepad and changed the file directory if that has to do with anything

**Comment by zaksabeast** [comment]
> I also opened the ips file in notepad and changed the file directory if that has to do with anything

Ah, there is a good chance that's the cause!  Notepad probably changed the file in a way that no longer makes it a valid IPS, which would cause the `svcBreak` issue in the crash dump.

Unfortunately if you want to use a save file in a different location you need to rebuild the patch with these instructions: [Building the patch for Dream Radar (All regions)](https://github.com/zaksabeast/DreamRadarCartRedirect#------building-the-patch-for-dream-radar-all-regions---).

**Comment by Spas120** [comment]
> > I also opened the ips file in notepad and changed the file directory if that has to do with anything
> 
> Ah, there is a good chance that's the cause! Notepad probably changed the file in a way that no longer makes it a valid IPS, which would cause the `svcBreak` issue in the crash dump.
> 
> Unfortunately if you want to use a save file in a different location you need to rebuild the patch with these instructions: [Building the patch for Dream Radar (All regions)](https://github.com/zaksabeast/DreamRadarCartRedirect#------building-the-patch-for-dream-radar-all-regions---).

Well I just wanted to change it so it wouldn't take so long to make a completely new patch

**Comment by Spas120** [comment]
I'm just going to use the already made ones I guess since it's hard to make a custom one

**Comment by zaksabeast** [comment]
Yep, sorry about that.  Modifying the file location requires the patch to change in a few other ways, and the build process takes care of those other changes automatically.
