### ISSUE TITLE
How to build the patchs poketransporter?

### ISSUE THREAD

**Issue by ASMC1301** [zaksabeast/DreamRadarCartRedirect#24]
I succeeded in getting the .code file.

But I got stuck in the next process..

I don’t understand “ Open a shell in the folder containing the renamed . bin file and other resources.”

How to open those??

.bin file won’t open..

**Comment by zaksabeast** [comment]
> I don’t understand “ Open a shell in the folder containing the renamed . bin file and other resources.”

"Open a shell" means use the terminal/command line.

Use your computer's terminal app to open the folder that has your .bin files.

> .bin file won’t open..

Don't open the .bin file.  Open the _folder_ that has the .bin file.

**Comment by ASMC1301** [comment]
I really appreciate you.

I think it's successful, but there's an error when it works.

![IMG_3859](https://github.com/zaksabeast/DreamRadarCartRedirect/assets/157446448/ec785e00-89ea-41e0-8134-80aeb8faf1d0)
