### ISSUE TITLE
Dream Radar Crash without Pokedex

### ISSUE THREAD

**Issue by stanuwu** [zaksabeast/DreamRadarCartRedirect#25]
Dream Radar will Crash on start when the Pokedex is not obtained yet on a White 2 save.
I assume this is not intended behaviour, and would not happen with a real cartridge.

**Comment by zaksabeast** [comment]
I was unable to reproduce the issue.

Here are the steps I took:
1. Delete the existing White 2 save
2. Create a new White 2 save and save the game at the earliest moment (before getting the Pokedex)
3. Open Dream Radar and transfer Pokemon
4. Open White 2 and try to receive Pokemon through the Unova Link

White 2 shows a message saying, "Play the game until you receive the Pokedex and then save the game."

Everything seems to work as expected.  Can you upload the Luma error binary or post a picture of the Luma error screen on your 3ds?

**Comment by stanuwu** [comment]
I have tried to replicate this again after deleting my save and making a new one, and was unable to. Not sure what could have caused it then, I just assumed it was the Pokedex, since it started working after I got it. Might have had something to do with the reboot that booting into TWL causes. Seems like an edge case or error on my end, sorry for the trouble,

**Comment by zaksabeast** [comment]
No problem
