### ISSUE TITLE
Add support on Pokemon Black and White for Poketransporter

### ISSUE THREAD

**Issue by chardrich** [zaksabeast/DreamRadarCartRedirect#3]
If possible, I would like to see if these are compatible to Poketransporter.

**Comment by zaksabeast** [comment]
Sorry for the late response.

The python script allows setting different cart Ids.  For example, `IRBO` is English Pokemon Black and `IRAO` is English Pokemon White:
```
python poke_redirect.py salmon IRAO /nds/saves/white.sav
```

I haven't tested those games, but I can't think of a reason they wouldn't work.

**Comment by zaksabeast** [comment]
I'm going to presume the above worked.  If not, please let me know.
