### ISSUE TITLE
Error Building Dream Radar Patch

### ISSUE THREAD

**Issue by HauntingSriracha** [zaksabeast/DreamRadarCartRedirect#31]
When executing the first given command in the shell for the folder, I receive an error. Here is my code and the output:

./armips radar.s -strequ SD_SAVE_PATH "/ROMS/NDS/saves/Pokemon Black Version 2.sav" -strequ GAME_ID "IREO"
ARMIPS64 Assembler v0.8.0 (Nov 19 2016 14:06:32) by Kingcom
sd-save-utils.s(61) error: Invalid ARM opcode
Aborting.

As you can see, I've altered the line of code to include the proper game ID and desired save path as instructed. I've attempted changing various thing including the name of the save path and the files in the folder. I figured it was worth asking the writer of the code before attempting to alter the source code or something.

**Comment by zaksabeast** [comment]
sd-save-utils.s(61)  uses `asciiz`, which was added in Armips version 0.10, released in 2018.  Based on your message, your build is from 2016.

There was a new release in 2020.  Try downloading [the latest armips](https://github.com/Kingcom/armips/releases/latest) and see if that solves the issue.

**Comment by HauntingSriracha** [comment]
That would make sense. I forgot that I downloaded my armips from a different source before realizing I had skipped it in the tutorial. I'll try that and report back

**Comment by HauntingSriracha** [comment]
So that did work for the first bit of code. I got stuck on the second and asked for help elsewhere, when someone pointed out I could download .ips patches that were already built by you, so I've done that. Thank you!
