### ISSUE TITLE
Building the patches help.

### ISSUE THREAD

**Issue by liketolike** [zaksabeast/DreamRadarCartRedirect#5]
The patch I built is invalid. Python 3.10
I type python poke_redirect.py pokear IRDO "/nds/saves/white2.sav" > code.ips in CMD, and the generated patch is invalid. 
[code.ips.txt](https://github.com/zaksabeast/DreamRadarCartRedirect/files/7807408/code.ips.txt)

**Comment by zaksabeast** [comment]
The patch you built looks correct.  Why do you think the patch is invalid?

Have you tried using [the release patches](https://github.com/zaksabeast/DreamRadarCartRedirect/releases/tag/v2.0.0)?

**Comment by liketolike** [comment]
Yes,it works very well

**Comment by zaksabeast** [comment]
Cool, it sounds like the issue is resolved.

**Comment by liketolike** [comment]
I see the reason. It's the problem of saving the path.
I should type "python poke_redirect.py pokear IRDO "/roms/nds/saves/white2.sav" > code.ips"
The tools you made are great!
